seed: 42
output_dir: logs
data:
  root: ./data
  name: CIFAR100
  label_level: fine
  download: true
  num_workers: 4
  batch_size: 32
  k_train: -1
model:
  name: "base" 
  hidden_features: 1024
  dropout: 0.1
  num_classes: 100
  depth: 2
train:
  epochs: 100
  lr: 1e-3
  weight_decay: 1e-4
  device: cuda
  log_interval: 235
  ckpt_interval: 1
  momentum : 0.9
