seed: 42
output_dir: logs
data:
  root: ./data
  name: CIFAR100
  label_level: fine
  download: true
  num_workers: 4
  batch_size: 64
  k_train: -1
  randaugment_enable: true
  randaugment_num_ops: 2
  randaugment_magnitude: 9
model:
  name: "densenet_bc_100_12"
  num_classes: 100
  dropout: 0.2
  growth_rate: 12
  bn_size: 4
  compression: 0.5
train:
  epochs: 300
  optimizer: sgd
  lr: 0.1
  weight_decay: 5e-4
  device: cuda
  log_interval: 235
  ckpt_interval: 1
  momentum: 0.9
  nesterov: true
  scheduler: cosine
  warmup_epochs: 5
  min_lr: 1e-5
  label_smoothing: 0.1
  mixup_alpha: 0.15
  cutmix_alpha: 1.0
  cutmix_prob: 0.3
  ema_decay: 0.999
  eval_with_ema: true
  save_best: true
  test_use_best: true
