seed: 42
output_dir: logs
data:
  root: ./data
  name: CIFAR100
  label_level: fine
  download: true
  num_workers: 4
  batch_size: 128
  k_train: -1
model:
  name: "pyramidnet"
  num_classes: 100
  dropout: 0.0            # dropout 제거
  pyramid_depth: 110
  pyramid_alpha: 270      # additive alpha 키우기
train:
  epochs: 300
  optimizer: sgd
  lr: 0.1                 # SGD 기본
  weight_decay: 5e-4
  device: cuda
  log_interval: 235
  ckpt_interval: 1
  momentum: 0.9
  nesterov: true
  scheduler: cosine
  warmup_epochs: 5
  min_lr: 0.0
  mixup_alpha: 0.2        # mixup 활성화
  label_smoothing: 0.1