seed: 42
output_dir: logs
data:
  root: ./data
  name: CIFAR100
  label_level: fine
  download: true
  num_workers: 4
  batch_size: 128
  k_train: -1
  randaugment_enable: true
  randaugment_num_ops: 2
  randaugment_magnitude: 9
model:
  name: "wideresnet"
  hidden_features: 1024
  dropout: 0.0
  num_classes: 100
  num_coarse_classes: 20
  depth: 2
  wrn_depth: 28 # WRN 전용
  widen_factor: 10 # WRN 전용
train:
  epochs: 300
  optimizer: sgd
  lr: 1e-1
  weight_decay: 5e-4
  device: cuda
  log_interval: 235
  ckpt_interval: 1
  momentum : 0.9
  nesterov: true
  scheduler: cosine
  warmup_epochs: 5
  min_lr: 1e-5
  label_smoothing: 0.0
  mixup_alpha: 0.2
  lambda_coarse: 0.5
  superclass_smooth_alpha: 0.1
 